version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: kobra
      MONGO_INITDB_ROOT_PASSWORD: fullstack
    volumes:
      - mongo-data:/data/db
    ports:
      - 27018:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kobra
      ME_CONFIG_MONGODB_ADMINPASSWORD: fullstack
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  eureka:
    image: surajk1995/eureka:3.0
    restart: always
    ports:
      - 8761:8761

  flightsearch:
    image: surajk1995/flightsearch:3.0
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - mongo

  flightbooking:
    image: surajk1995/flightbooking:3.0
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - mongo

  checkin:
    image: surajk1995/checkin:3.0
    restart: always
    ports:
      - 8083:8083
    depends_on:
      - eureka
      - mongo

  payment:
    image: surajk1995/payment:3.0
    restart: always
    ports:
      - 8084:8084
    depends_on:
      - eureka
      - mongo

  admin:
    image: surajk1995/admin:3.0
    restart: always
    ports:
      - 8085:8085
    depends_on:
      - eureka
      - mongo
    
  security:
    image: surajk1995/security:3.0
    restart: always
    ports:
      - 8086:8086
    depends_on:
      - eureka
      - mongo

  gateway:
    image: surajk1995/gateway:3.0
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - eureka
      - mongo
      - flightsearch
      - flightbooking
      - checkin
      - admin
      - security
      - payment

  flight-ui:
    image: surajk1995/angularproject
    restart: always
    ports:
      - 80:80

volumes:
  mongo-data: